version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    volumes:
      - ./services/mosquitto:/mosquitto
      #- ./volumes/server/credentials/server:/mosquitto/certs
    expose:
        - "8883"
        - "9001"
    ports:
        - "8883:8883"
        - "9001:9001"
