# set base image (host OS)
FROM python:3.7-slim

ARG DB_HOST
ARG DB_USER
ARG DB_PWD
ARG DB_NAME
ARG DB_PORT
ARG DB_ENGINE

# set the working directory in the container
WORKDIR /code

ENV FLASK_APP api
ENV FLASK_RUN_HOST 0.0.0.0
ENV FLASK_ENV development

ENV DB_HOST $DB_HOST
ENV DB_USER $DB_USER
ENV DB_PWD $DB_PWD
ENV DB_NAME $DB_NAME
ENV DB_PORT $DB_PORT
ENV DB_ENGINE $DB_ENGINE

# copy the dependencies file to the working directory
COPY requirements.txt requirements.txt

# install dependencies
RUN pip install -r requirements.txt

COPY . .

CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0"]

