version: '3'

services:
  portal-iot:
    image: portal-iot
    container_name: portal-iot
    env_file:
      - ../services/portal-iot/.env
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - SQLITE_PATH=${SQLITE_PATH}
    ports:
      - 5000:5000
    volumes: 
      - '.:/code'
      - '../volumes/db:/code/db'

