version: '3'

services:
  portal-iot:
    image: iot-server
    container_name: iot-server
    env_file:
      - ../services/server/.env
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - SQLITE_PATH=${SQLITE_PATH}
    ports:
      - 5000:5000
    volumes: 
      - '.:/code'
      - '../services/server/conf:/code/conf'
      - '../volumes/db:/code/db'
      - '../volumes/server/storage:/code/portal/storage/local'
      - '../volumes/server/credentials/server:/code/portal/storage/credentials/server'
      - '../volumes/server/credentials/clients:/code/portal/storage/credentials/clients'

